[2025-02-18T19:30:41.042+0000] {processor.py:186} INFO - Started process (PID=46) to work on /opt/airflow/dags/example-naavre-converted.py
[2025-02-18T19:30:41.044+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/example-naavre-converted.py for tasks to queue
[2025-02-18T19:30:41.051+0000] {logging_mixin.py:190} INFO - [2025-02-18T19:30:41.050+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/example-naavre-converted.py
[2025-02-18T19:30:41.467+0000] {logging_mixin.py:190} INFO - [2025-02-18T19:30:41.464+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/example-naavre-converted.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example-naavre-converted.py", line 22, in <module>
    list_py_set = DockerOperator(
                  ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 256, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 959, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: list_py_set). Invalid arguments were:
**kwargs: {'volumes': ['/tmp/data:/tmp/data']}
[2025-02-18T19:30:41.470+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/example-naavre-converted.py
[2025-02-18T19:30:41.514+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/example-naavre-converted.py took 0.479 seconds
[2025-02-18T19:31:12.324+0000] {processor.py:186} INFO - Started process (PID=110) to work on /opt/airflow/dags/example-naavre-converted.py
[2025-02-18T19:31:12.325+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/example-naavre-converted.py for tasks to queue
[2025-02-18T19:31:12.329+0000] {logging_mixin.py:190} INFO - [2025-02-18T19:31:12.328+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/example-naavre-converted.py
[2025-02-18T19:31:12.425+0000] {logging_mixin.py:190} INFO - [2025-02-18T19:31:12.423+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/example-naavre-converted.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example-naavre-converted.py", line 22, in <module>
    list_py_set = DockerOperator(
                  ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 256, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 959, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: list_py_set). Invalid arguments were:
**kwargs: {'volumes': ['/tmp/data:/tmp/data']}
[2025-02-18T19:31:12.425+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/example-naavre-converted.py
[2025-02-18T19:31:12.436+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/example-naavre-converted.py took 0.122 seconds
[2025-02-18T19:31:42.534+0000] {processor.py:186} INFO - Started process (PID=174) to work on /opt/airflow/dags/example-naavre-converted.py
[2025-02-18T19:31:42.535+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/example-naavre-converted.py for tasks to queue
[2025-02-18T19:31:42.536+0000] {logging_mixin.py:190} INFO - [2025-02-18T19:31:42.536+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/example-naavre-converted.py
[2025-02-18T19:31:42.609+0000] {logging_mixin.py:190} INFO - [2025-02-18T19:31:42.608+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/example-naavre-converted.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example-naavre-converted.py", line 22, in <module>
    list_py_set = DockerOperator(
                  ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 256, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 959, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: list_py_set). Invalid arguments were:
**kwargs: {'volumes': ['/tmp/data:/tmp/data']}
[2025-02-18T19:31:42.609+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/example-naavre-converted.py
[2025-02-18T19:31:42.622+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/example-naavre-converted.py took 0.093 seconds
[2025-02-18T19:32:12.878+0000] {processor.py:186} INFO - Started process (PID=237) to work on /opt/airflow/dags/example-naavre-converted.py
[2025-02-18T19:32:13.051+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/example-naavre-converted.py for tasks to queue
[2025-02-18T19:32:13.059+0000] {logging_mixin.py:190} INFO - [2025-02-18T19:32:13.058+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/example-naavre-converted.py
[2025-02-18T19:32:13.197+0000] {logging_mixin.py:190} INFO - [2025-02-18T19:32:13.193+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/example-naavre-converted.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example-naavre-converted.py", line 22, in <module>
    list_py_set = DockerOperator(
                  ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 256, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 959, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: list_py_set). Invalid arguments were:
**kwargs: {'volumes': ['/tmp/data:/tmp/data']}
[2025-02-18T19:32:13.198+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/example-naavre-converted.py
[2025-02-18T19:32:13.230+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/example-naavre-converted.py took 0.375 seconds
[2025-02-18T19:32:43.643+0000] {processor.py:186} INFO - Started process (PID=301) to work on /opt/airflow/dags/example-naavre-converted.py
[2025-02-18T19:32:43.645+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/example-naavre-converted.py for tasks to queue
[2025-02-18T19:32:43.650+0000] {logging_mixin.py:190} INFO - [2025-02-18T19:32:43.649+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/example-naavre-converted.py
[2025-02-18T19:32:43.750+0000] {logging_mixin.py:190} INFO - [2025-02-18T19:32:43.747+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/example-naavre-converted.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example-naavre-converted.py", line 22, in <module>
    list_py_set = DockerOperator(
                  ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 256, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 959, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: list_py_set). Invalid arguments were:
**kwargs: {'volumes': ['/tmp/data:/tmp/data']}
[2025-02-18T19:32:43.750+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/example-naavre-converted.py
[2025-02-18T19:32:43.761+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/example-naavre-converted.py took 0.133 seconds
[2025-02-18T19:33:14.525+0000] {processor.py:186} INFO - Started process (PID=365) to work on /opt/airflow/dags/example-naavre-converted.py
[2025-02-18T19:33:14.529+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/example-naavre-converted.py for tasks to queue
[2025-02-18T19:33:14.538+0000] {logging_mixin.py:190} INFO - [2025-02-18T19:33:14.538+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/example-naavre-converted.py
[2025-02-18T19:33:14.650+0000] {logging_mixin.py:190} INFO - [2025-02-18T19:33:14.647+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/example-naavre-converted.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example-naavre-converted.py", line 22, in <module>
    list_py_set = DockerOperator(
                  ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 256, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 959, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: list_py_set). Invalid arguments were:
**kwargs: {'volumes': ['/tmp/data:/tmp/data']}
[2025-02-18T19:33:14.652+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/example-naavre-converted.py
[2025-02-18T19:33:14.669+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/example-naavre-converted.py took 0.163 seconds
[2025-02-18T19:33:44.826+0000] {processor.py:186} INFO - Started process (PID=429) to work on /opt/airflow/dags/example-naavre-converted.py
[2025-02-18T19:33:44.833+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/example-naavre-converted.py for tasks to queue
[2025-02-18T19:33:44.837+0000] {logging_mixin.py:190} INFO - [2025-02-18T19:33:44.837+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/example-naavre-converted.py
[2025-02-18T19:33:44.980+0000] {logging_mixin.py:190} INFO - [2025-02-18T19:33:44.966+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/example-naavre-converted.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example-naavre-converted.py", line 22, in <module>
    list_py_set = DockerOperator(
                  ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 256, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 959, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: list_py_set). Invalid arguments were:
**kwargs: {'volumes': ['/tmp/data:/tmp/data']}
[2025-02-18T19:33:44.982+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/example-naavre-converted.py
[2025-02-18T19:33:44.999+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/example-naavre-converted.py took 0.187 seconds
[2025-02-18T19:34:15.666+0000] {processor.py:186} INFO - Started process (PID=493) to work on /opt/airflow/dags/example-naavre-converted.py
[2025-02-18T19:34:15.671+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/example-naavre-converted.py for tasks to queue
[2025-02-18T19:34:15.677+0000] {logging_mixin.py:190} INFO - [2025-02-18T19:34:15.676+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/example-naavre-converted.py
[2025-02-18T19:34:15.819+0000] {logging_mixin.py:190} INFO - [2025-02-18T19:34:15.816+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/example-naavre-converted.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example-naavre-converted.py", line 22, in <module>
    list_py_set = DockerOperator(
                  ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 256, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 959, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: list_py_set). Invalid arguments were:
**kwargs: {'volumes': ['/tmp/data:/tmp/data']}
[2025-02-18T19:34:15.819+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/example-naavre-converted.py
[2025-02-18T19:34:15.840+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/example-naavre-converted.py took 0.194 seconds
